### ISSUE TITLE
Better representation of missing values across columns

### ISSUE THREAD

**Issue by adn4n** [jtablesaw/tablesaw#82] opened 2016-08-14 03:03 UTC
When creating tables from csv files, missing values for SHORT_INT, INTEGER, LONG_INT, FLOAT and CATEGORY columns are represented as `-32768`, `-2147483648`, `-9223372036854775808`, `NaN`, and `""` respectively.

The representation of `-32768`, `-2147483648`, `-9223372036854775808` and `NaN` outputs incorrect (and `NaN` for FLOAT column) results for almost all of descriptive statistics functions, e.g., `sum()`, `min()` and `mean()`. I was wondering if there is a better (and more consistent) way of representing missing values across column types?

**Comment by lwhite1** [comment] 2016-08-14 13:42
As these columns are stored as primitives to minimize memory use, there is no better representation that I know of. If you know of one, please LMK.  

You are correct, however, that missing data handling is broken. There is an open issue to fix it (#51).  Fixing will mean modifying methods to skip missing data when calculating or rendering over the values of a column.

**Comment by lwhite1** [comment] 2017-08-13 14:23
closing as a duplicate of #51

**Closed by lwhite1** 2017-08-13 14:23 UTC
