### ISSUE TITLE
Calling .unique then .sortAscending results in all 0s.

### ISSUE THREAD

**Issue by g-r-t** [jtablesaw/tablesaw#775] opened 2020-03-07 21:30 UTC
I encountered an issue that seems to be related to #586. However, #586 was marked as closed in August 2019, and I'm experiencing this issue using the latest 0.37.3 jar from Maven Central. 

The issue is when .sortAscending is called on a DoubleColumn produced by a call to .unique, the result is all 0s. 

I created a short, simple example that illustrates the issue:
```
        double[] ds = { 5, 4, 3, 2, 1, 5, 4, 3, 2, 1 };
        DoubleColumn unq = DoubleColumn.create("All 0s", ds).unique();
        System.out.println(Arrays.toString(unq.asDoubleArray()));
        unq.sortAscending();
        System.out.println(Arrays.toString(unq.asDoubleArray()));

        System.out.println();
        
        // Must make a copy here, otherwise sorting will expand with 0s.
        unq = DoubleColumn.create("All 0s", ds).unique().copy();
        System.out.println(Arrays.toString(unq.asDoubleArray()));
        unq.sortAscending();
        System.out.println(Arrays.toString(unq.asDoubleArray()));
```
The output from running this is:
```
[1.0, 4.0, 3.0, 5.0, 2.0]
[0.0, 0.0, 0.0, 0.0, 0.0]

[1.0, 4.0, 3.0, 5.0, 2.0]
[1.0, 2.0, 3.0, 4.0, 5.0]
```

As featured in the example code, it's possible to work around the issue by calling .copy on the DoubleColumn produced by the call to .unique.

**Comment by benmccann** [comment] 2020-03-09 23:19
Thanks. I've added a test for this here: https://github.com/jtablesaw/tablesaw/commit/6febe7d061ca28dd5913eb2bcd5a99668fdec554

I'm guessing that the issue is with `sortAscending`. It seems to work if I change the code there:

```
  @Override
  public DoubleColumn sortAscending() {
    double[] arr = asDoubleArray(); 
    DoubleArrays.parallelQuickSort(arr);
    return DoubleColumn.create(name(), arr);
  }
```

Though the way I changed the code changes the signature and requires the other methods to be updated as well. I'm not sure I'll have time to fix, but I'd be happy to review a PR if you want to take a stab at it.

**Comment by emilianbold** [comment] 2020-03-10 10:53
I just looked into this.

The problem is the way `data.elements()` is used. `DoubleArrayList.elements()` exposes the *internal* data.

According to the docs that data is not what you expect http://fastutil.di.unimi.it/docs/it/unimi/dsi/fastutil/doubles/DoubleArrayList.html#elements() :

> Instances of this class represent a list with an array that is enlarged as needed when new entries are created (by doubling its current length), but is never made smaller (even on a clear()). 

By default a column creates `data = new DoubleArrayList(DEFAULT_ARRAY_SIZE)` which has all zeros. Getting that array and sorting it will push all those zeros in front:

```java
        DoubleArrayList list = new DoubleArrayList(128);
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(4);
        System.out.println(Arrays.toString(list.elements()));
//[1.0, 2.0, 3.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        DoubleArrays.parallelQuickSort(list.elements());
        System.out.println(Arrays.toString(list.elements()));
//[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 2.0, 3.0, 4.0]
```

**Comment by benmccann** [comment] 2020-03-10 17:52
Thanks to @emilianbold this is now fixed in `master` and will be part of the next release

**Closed by benmccann** 2020-03-10 17:52 UTC
Labels: bug, core
