### ISSUE TITLE
Error while Importing data from RDBMS

### ISSUE THREAD

**Issue by ansarisam** [jtablesaw/tablesaw#411] opened 2018-11-10 17:15 UTC
I started playing with this jtablesaw library -- looks very interesting.

**Comment by ansarisam** [comment] 2018-11-10 17:35
I upgraded guava to version 27 and the above error is gone. Now I am facing a different problem. Looks like, its interpreting column data type incorrectly.
Here is my code snippet:
```
ResultSet rs = st.executeQuery(sql);
Table dataTable = Table.read().db(rs, tableName);
System.out.println(dataTable.summary());
```

Error: 
Exception in thread "main" java.lang.IllegalArgumentException: Could not append class java.lang.Long
	at tech.tablesaw.api.DoubleColumn.appendObj(DoubleColumn.java:409)
	at tech.tablesaw.api.DoubleColumn.appendObj(DoubleColumn.java:35)
	at tech.tablesaw.io.jdbc.SqlResultSetReader.read(SqlResultSetReader.java:105)
	at tech.tablesaw.io.DataFrameReader.db(DataFrameReader.java:66)

**Comment by benmccann** [comment] 2018-11-11 22:07
@gregorco 's pending PR https://github.com/jtablesaw/tablesaw/pull/400 may fix this

**Comment by lwhite1** [comment] 2018-11-28 20:13
@ansarisam. PR #400 has been merged. Please LMK if you're still having this issue.

**Comment by lwhite1** [comment] 2018-12-03 15:11
closing. Will reopen if I hear that the problem is not fixed.

**Closed by lwhite1** 2018-12-03 15:11 UTC
