### ISSUE TITLE
CVS filename starting with number isn't read

### ISSUE THREAD

**Issue by leonardotrp** [jtablesaw/tablesaw#492] opened 2019-03-12 00:37 UTC
First of all congratulations for the project, especially for the integration with Plotly, tool with which I already have some experience.

Reading a CVS file with a name that starts with number does not work, as shown in the code sample below. Just I start the filename with a letter, that reading works correctly.

-------------------------------
```
// WRONG
String cvsFile = "PATH\\1_filename.csv"
Table table = Table.read().csv(cvsFile);
System.err.println(table.printAll()); // print '1_filename.cvs'
```
-------------------------------
```
// RIGHT
String cvsFile = "PATH\\filename.csv"
Table table = Table.read().csv(cvsFile);
System.err.println(table.printAll()); // OK! print all cvs contents
```
-------------------------------

I'm using the version 0.31.0

Is this a bug? I believe this is the same problem reported at closed issue https://github.com/jtablesaw/tablesaw/issues/386

**Comment by benmccann** [comment] 2019-03-12 05:03
`CsvReaderTest` reads a file named `10001_columns.csv`, so I doubt that the issues is that the file name starts with a 1. Or at least it doesn't happen on my machine. Perhaps it only happens on Windows?

What if you pass in a `File` instead of a `String`?

What if you try with 0.32.2?

**Comment by benmccann** [comment] 2019-03-22 05:28
I'm closing this because I can't reproduce. Please feel free to provide additional details and it can be reopened

**Closed by benmccann** 2019-03-22 05:28 UTC
