### ISSUE TITLE
Column type detection strategy for numbers ending with .0

### ISSUE THREAD

**Issue by larshelge** [jtablesaw/tablesaw#747] opened 2020-01-30 14:53 UTC
First of all, thanks for an excellent library!

This issue relates to the table column type detection. My use-case is having TableSaw detect the column types of a CSV data file. That information is used to create a table in AWS Redshift and later ingest the CSV file into the table. I am mapping TableSaw `INTEGER` column type to Redshift `INTEGER` data type.

I came across a corner case in which TableSaw detects numbers ending with ".0", such as "1613.0" or "962.0", as integer column type. This is arguably correct, but fails in my use-case, as AWS Redshift does not accept such values as integers and fails during data load.

Would this case be worthy of a configurable read option, to control whether numbers with zero value decimals will be mapped to integer or floating point types? 

`ReadOptions.zeroDecimalNumberAsFloat` or a more succinct name would be great.

Tablesaw version 0.37.3.

**Comment by benmccann** [comment] 2020-01-30 16:16
This looks like a duplicate of https://github.com/jtablesaw/tablesaw/issues/732

So Redshift and TableSaw are both reading from the CSV and you need the column types to match? It might help to explain the use case the more. Why does every single cell end in ".0"?

**Comment by larshelge** [comment] 2020-01-30 21:10
Thanks for the quick reply. It is _not quite_ the same problem, although related. `732` is about the sample phase returning the wrong result, i.e. integer when the data column contains double values with arbitrary decimal values.

This issue is about the sampling arguably returning the correct result (integer), but in the case of matching to other systems such as Redshift, should preferably return a floating type (i.e. double). I would argue that `100.0` should be considered a double, but that might be an opinion.

That said, since there seems to be a use-case for treating `100.0` as a double, perhaps it could deserve an option; either a specific setting such as `zeroDecimalsAsFloatingPoint` or a "mode" setting such as `ReadOptions.parsingMode(STRICT | LENIENT)`. 

My preference would be to change the behavior but I realize that is not backwards compatible and debatable. Second preference would be an option.

To answer your question - I don't know. We are building a data platform where users may upload their own CSV files and so we need to handle less-than-perfect data files. Thanks again!

**Comment by larshelge** [comment] 2020-01-30 22:24
Created PR for `ReadOptions.ignoreZeroDecimals` here #748.

**Comment by benmccann** [comment] 2020-04-13 15:22
Closed by https://github.com/jtablesaw/tablesaw/pull/748

**Closed by benmccann** 2020-04-13 15:22 UTC
