### ISSUE TITLE
Error reading iris and baseball csv file

### ISSUE THREAD

**Issue by fdas3213** [jtablesaw/tablesaw#412] opened 2018-11-12 19:35 UTC
I try to read iris csv file and the baseball csv file provided in the github data page. I used following code to read it
```
try{     //filename is a string indicating the csv file name
            Table data = Table.read().csv(filename);
        }catch(IOException ioe){
            ioe.printStackTrace();
        }
```
And I run into following error 
```
Exception in thread "main" com.univocity.parsers.common.TextParsingException: java.lang.ArrayIndexOutOfBoundsException - 512
Hint: Number of columns processed may have exceeded limit of 512 columns. Use settings.setMaxColumns(int) to define the maximum number of columns your input can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the input format you are trying to parse
Parser Configuration: CsvParserSettings:
	Auto configuration enabled=true
	Autodetect column delimiter=false
	Autodetect quotes=false
	Column reordering enabled=true
	Delimiters for detection=null
	Empty value=null
	Escape unquoted values=false
	Header extraction enabled=null
	Headers=null
	Ignore leading whitespaces=true
	Ignore leading whitespaces in quotes=false
	Ignore trailing whitespaces=true
	Ignore trailing whitespaces in quotes=false
	Input buffer size=1048576
	Input reading on separate thread=true
	Keep escape sequences=false
	Keep quotes=false
	Length of content displayed on error=-1
	Line separator detection enabled=false
	Maximum number of characters per column=4096
	Maximum number of columns=512
	Normalize escaped line separators=true
	Null value=null
	Number of records to read=all
	Processor=none
	Restricting data in exceptions=false
	RowProcessor error handler=null
	Selected fields=none
	Skip bits as whitespace=true
	Skip empty lines=true
	Unescaped quote handling=nullFormat configuration:
	CsvFormat:
		Comment character=#
		Field delimiter=,
		Line separator (normalized)=\n
		Line separator sequence=\r\n
		Quote character="
		Quote escape character="
		Quote escape escape character=null
Internal state when error was thrown: line=0, column=513, record=0, charIndex=2256
	at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:369)
	at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:595)
	at tech.tablesaw.io.csv.CsvReader.detectColumnTypes(CsvReader.java:472)
	at tech.tablesaw.io.csv.CsvReader.getColumnTypes(CsvReader.java:209)
	at tech.tablesaw.io.csv.CsvReader.read(CsvReader.java:121)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:62)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:58)
	at tech.tablesaw.io.DataFrameReader.csv(DataFrameReader.java:34)
```
When I removed the last column of iris dataset, which is a string column indicating the species, things worked. But when I tried to read the raw iris.csv or baseball.csv, this error just shows up. Can anyone please help me figure out what to do? Thank you

**Comment by lwhite1** [comment] 2018-11-27 00:13
This seems to be a duplicate of #395

**Comment by lwhite1** [comment] 2018-11-27 00:18
Looks like the fix for #395 is not in the latest release, so if this is still an issue you would need to build from master until that release happens.

**Comment by benmccann** [comment] 2018-11-27 16:47
I think the fix is in the latest release. @fdas3213 can you make sure you're using the latest version 0.30.1 and try again?

**Comment by lwhite1** [comment] 2018-11-28 20:10
Closing as fixed; @fdas3213, please re-open if it's still an issue for you.

**Closed by lwhite1** 2018-11-28 20:10 UTC
