### ISSUE TITLE
The first row from the table is not returned

### ISSUE THREAD

**Issue by Indraja22** [jtablesaw/tablesaw#1035] opened 2021-11-05 21:13 UTC
Please note first row is getting skipped.
Database : MySQL
Tablesaw dependency : 
<dependency>
			<groupId>tech.tablesaw</groupId>
			<artifactId>tablesaw-core</artifactId>
			<version>0.42.0</version>
		</dependency>

Line of code : System.out.println(Table.read().db(resultSet).printAll());

Result Obtained  :
  id   |                  description                   |        title        |
-------------------------------------------------------------------------------
 6670  |  This is a complete JavaScript Expert course.  |  JavaScript Expert  |
 6671  |        This is a complete Java Expert course.  |       Java  Expert  |
 6679  |    This is a complete Java DSA Expert course.  |    Java DSA Expert  |
 9990  |  This is a complete JavaScript Basics course.  |  JavaScript Basics  |

Actual Data in DB :
mysql> select * from demo_api.course;
+------+----------------------------------------------+-------------------+
| id   | description                                  | title             |
+------+----------------------------------------------+-------------------+
| 2334 | This is a complete CPP DSA course.           | CPP DSA           |
| 6670 | This is a complete JavaScript Expert course. | JavaScript Expert |
| 6671 | This is a complete Java Expert course.       | Java  Expert      |
| 6679 | This is a complete Java DSA Expert course.   | Java DSA Expert   |
| 9990 | This is a complete JavaScript Basics course. | JavaScript Basics |
+------+----------------------------------------------+-------------------+

**Comment by lwhite1** [comment] 2021-11-14 14:20
Did you directly examine the data in the java sql ResultSet to see if it was correct?

**Comment by lwhite1** [comment] 2022-03-27 00:31
closing as can't reproduce

**Closed by lwhite1** 2022-03-27 00:31 UTC
