### ISSUE TITLE
CSV import: IntParser removes decimal when value ends with ".0" during parsing

### ISSUE THREAD

**Issue by szabolcskarolyi** [jtablesaw/tablesaw#732] opened 2019-12-09 15:30 UTC
We have a case when our input csv has a column that has many values of "0.0" and some real double values.
Problem is that during the sample phase the columnType is set to Integer because the sample values pass in the parse test due to the check at:
https://github.com/jtablesaw/tablesaw/blob/master/core/src/main/java/tech/tablesaw/columns/numbers/IntParser.java#L28

Wondering if that check could be removed or be optional.

We came up with a solution, where we created a custom IntColumnType and IntParser, trying to set columnTypesToDetect in ReadOptions, however it looks like the setter is missing in CsvReadOptions.Builder so the default columnTypesToDetect list cannot be overriden.
We used reflection, but would like to avoid this solution.
Ideal would be to handle "x.0" values as double instead.

We would appreciate your help :)
Szabolcs

**Comment by benmccann** [comment] 2019-12-09 17:18
If I understand correctly, it seems to me like the issue isn't that 0.0 is being treated as an integer, but that the real double values are not being encountered during sampling. You could either disable sampling or you could specify that the column is a double column.

**Comment by szabolcskarolyi** [comment] 2019-12-10 09:10
You are right, but we cannot do either. We have like 200+ columns that makes difficult to specify column types and disable sampling leads to memory issues as our csvs are quite large.

**Comment by benmccann** [comment] 2019-12-10 16:12
What if we made it so that you can specify just some column types by name or index?

**Comment by lwhite1** [comment] 2020-02-21 18:36
@szabolcskarolyi 
> You are right, but we cannot do either.

I'm not sure why having 200 columns prevents your specifying column types. Unless the columns change constantly, it's not a lot of work.

**Comment by lwhite1** [comment] 2020-02-23 19:19
> What if we made it so that you can specify just some column types by name or index?

This seems like a good idea, but I don't think I would do it by index, since the main complaint I've seen about providing column type defs is for files that change their shape over time.

**Comment by benmccann** [comment] 2020-04-13 15:23
Closed by https://github.com/jtablesaw/tablesaw/pull/748

**Closed by benmccann** 2020-04-13 15:23 UTC
