### ISSUE TITLE
tech.tablesaw.api.DateTimeColumn cannot be cast to tech.tablesaw.api.DateCol

### ISSUE THREAD

**Issue by wangpo1991** [jtablesaw/tablesaw#813] opened 2020-06-19 12:03 UTC
when I choose the 
tech.tablesaw.plotly.api.TimeSeriesPlot
public static Figure create(String title, Table table, String dateColX, String yCol, String groupCol)
for support my datePattern as "yyyy-MM-dd HH:mm" 
the  origin code throw exception
tech.tablesaw.api.DateTimeColumn cannot be cast to tech.tablesaw.api.DateCol
so I change the code where 
tech.tablesaw.plotly.api.TimeSeriesPlot
          ScatterTrace.builder(t.dateColumn(dateColX), t.numberColumn(yCol))
to 
          ScatterTrace.builder(t.stringColumn(dateColX), t.numberColumn(yCol))

it run ok 
where is my fault with using the api ,please tell me ,thx.

**Comment by benmccann** [comment] 2020-06-19 12:09
Please make sure you're using the latest (0.38.1) as some related issues have been fixed. Otherwise I think this is a duplicate of https://github.com/jtablesaw/tablesaw/issues/782

**Closed by benmccann** 2020-06-19 12:09 UTC
