### ISSUE TITLE
How much data can tablesaw store at most?

### ISSUE THREAD

**Issue by devywb** [jtablesaw/tablesaw#290] opened 2018-05-30 09:06 UTC
How much data can tablesaw store at most?

**Comment by devywb** [comment] 2018-05-30 10:29
My program prompts this error message：java.lang.OutOfMemoryError: Requested array size exceeds VM limit

**Comment by devywb** [comment] 2018-05-30 10:31
code snippet：

`
@RequestMapping("appentSaw")
	public void appentSaw() {
		try {
			String path = ContextLoader.getCurrentWebApplicationContext().getServletContext().getRealPath("/") + File.separator + "guocereport"; // 项目根目录下的report文件夹
			tech.tablesaw.api.Table table = TablesawUtil.read(ReportNameConstant.IP_COUNT);
			table.append(table);
			
			/*Map<String, String> header = new LinkedHashMap<>();
			header.put("ip", "IP");
			header.put("count", "次数");
			header.put("date", "日期");
			
			String headerContent = TablesawUtil.getHeaderContent(header);
			String content = TablesawUtil.getTableContent(table);
			table = tech.tablesaw.api.Table.read().csv(headerContent + content + content, ReportNameConstant.IP_COUNT);*/
			table.save(path);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
`
TablesawUtil.java
`
	/**
	 * 读取 saw 文件
	 * @param monthStr
	 * @param tableName
	 * @return
	 */
	public static Table read(String tableName) {
		Table table = null;
		// 创建月份文件夹。文件夹存在则直接创建子文件
		String reportFilePath = createReportFile();
		String filePath = reportFilePath + File.separator +tableName + SUFFIX ;
		File file = new File(filePath);
		if(file.exists() && file.isDirectory()) {
			try {
				table = Table.readTable(filePath);
			} catch (Exception e) {
				System.out.println("读取" + tableName + "文件时出现异常");
				e.printStackTrace();
			}
		}
		return table;
	}
`

**Comment by lwhite1** [comment] 2018-05-31 11:02
How much data you can work with in Tablesaw depends on how much memory you
allocate, and what you're trying to do with the data. Some operations are
necessarily more costly in memory than others. So there is no general
answer to the question posed.

If you haven't already tried it, setting the memory allocated to the JVM
using Xmx to something larger will certainly help.

**Comment by devywb** [comment] 2018-06-01 08:31
The wrong code is Tech.tablesaw.io.csv.CsvReader 156 lines

````
byte[] bytes = options.reader() != null
            ? CharStreams.toString(options.reader()).getBytes() : null;
````

**Comment by lwhite1** [comment] 2018-06-01 23:46
I see. Thanks for the detailed explanation. I will look into it.

**Comment by lwhite1** [comment] 2018-06-06 14:55
@devywb I looked at the source for CsvReadOptions.Builder and saw this comment around the method you're using:
```
    /**
     * This method buffers the entire InputStream. Use the method taking a File for large input
     */
```
Are you able to use the version of the API for Files?  For example:

```
Table.read().csv(String fileName);
Table.read().csv(File file);
```
I will look into why the system is buffering the input stream. I'm guessing there is a good reason, but i didn't write this part so I need dig a bit.

**Comment by benmccann** [comment] 2018-06-06 15:21
The reason was because we go through the input stream once to determine the column types and then a second time to read the data into the columns and input streams can't necessarily be read from the beginning twice

**Comment by lwhite1** [comment] 2018-06-06 15:22
Thanks!

**Comment by lwhite1** [comment] 2018-06-06 15:45
As there does not seem to be a solution, I'm closing.

**Closed by lwhite1** 2018-06-06 15:45 UTC

**Comment by lwhite1** [comment] 2018-08-22 19:14
I spoke too soon. I have made a work-around for this issue. When you read from an input stream and run out of memory, you can use one of two methods to prevent the entire file from being cached:

1. You can pass in a file or fileName, rather than a stream or reader, or 
2. You can provide the column type array.  We need to read a file into memory as described above when you give us a stream or reader and we have to detect column types. If you provide the column types that part of the code can be skipped. 

The second option lets you read large files as streams when necessary, as when you're reading from a remote URL or from an AWS bucket.

**Comment by Friendwork** [comment] 2020-01-20 07:50
I have similar problem when trying to load ~ 5GB table data to memory. The temporary solution is stream it into file. There should have a lazy loading such as combination of resultset and stream

**Comment by wmj123456** [comment] 2022-02-17 08:25
I have similar problem in the function ：tech.tablesaw.aggregate.Summarizer.by
OutOfMemoryError is reported in this method, is there a solution?

**Comment by lwhite1** [comment] 2022-02-17 19:58
It's very hard to say without more details. I need to see the code and a
stack trace at a minimum. A reproducible example is best.

**Comment by wmj123456** [comment] 2022-02-21 02:17
I have a csv file with a size of 3G, and I need to count the number of unique data in a certain field. I use the Summar.by() method and report an OutMemoryError error :
Exception Class:class java.lang.OutOfMemoryError
Exception info:Java heap space
Exception StackTrace start:
java.util.Arrays.copyOfRange(Arrays.java:3664)
java.lang.String.<init>(String.java:207)
java.lang.String.substring(String.java:1969)
java.lang.String.subSequence(String.java:2003)
com.google.common.base.Splitter$SplittingIterator.computeNext(Splitter.java:611)
com.google.common.base.Splitter$SplittingIterator.computeNext(Splitter.java:523)
com.google.common.base.AbstractIterator.tryToComputeNext(AbstractIterator.java:67)
com.google.common.base.AbstractIterator.hasNext(AbstractIterator.java:62)
com.google.common.base.Splitter.splitToList(Splitter.java:417)
tech.tablesaw.table.TableSliceGroup.splitGroupingColumn(TableSliceGroup.java:156)
tech.tablesaw.table.TableSliceGroup.aggregate(TableSliceGroup.java:216)
tech.tablesaw.table.TableSliceGroup.aggregate(TableSliceGroup.java:178)
tech.tablesaw.aggregate.Summarizer.summarize(Summarizer.java:344)
tech.tablesaw.aggregate.Summarizer.by(Summarizer.java:156)

**Comment by lwhite1** [comment] 2022-02-21 02:28
If you only need to count the number of unique values, the countUnique()
method on Column is your best bet.

**Comment by wmj123456** [comment] 2022-02-21 06:16
And there is also a case of deduplicating counts according to multiple columns

**Comment by lwhite1** [comment] 2022-02-22 00:29
Try table.dropDuplicateRows()

**Comment by wmj123456** [comment] 2022-02-22 03:08
Doesn't this method need to sort the data?
/** Returns the unique records in this table Note: Uses a lot of memory for a sort */

**Comment by lwhite1** [comment] 2022-02-22 06:16
Have you tried allocating more memory?
Have you considered dropping some columns or rows?

The memory usage of different methods is often highly dependent on the
number of columns, their types, and the cardinality of the values.

Without knowing the details of the data and what you are trying to do, I
can only guess at solutions to your problem.

**Comment by lwhite1** [comment] 2022-03-26 21:39
Just a comment that the method dropDuplicateRows() is being rewritten to use less memory.
